DROP TABLE IF EXISTS book_data;

CREATE TABLE book_data (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)        NOT NULL,
    author        VARCHAR(255)        NOT NULL,
    isbn          VARCHAR(32)         NOT NULL,
    publish_date  DATE                NOT NULL,
    price         DECIMAL(10,2)       NOT NULL,
    book_type     VARCHAR(32)         NOT NULL
);

CREATE UNIQUE INDEX ux_book_data_isbn ON book_data(isbn);