package za.co.catalogue.management.model;

import lombok.Data;
import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Entity class representing a book in the catalogue.
 * 
 * <p>This JPA entity maps to the "book_data" table in the database.
 * It enforces uniqueness constraints:
 * <ul>
 *   <li>ISBN must be unique across all books</li>
 *   <li>Combination of name, author, and publish date must be unique</li>
 * </ul>
 * 
 * <p>The ISBN is immutable once set and is generated server-side.
 */
@Entity
@Table(name = "book_data",
        uniqueConstraints = {
        @UniqueConstraint(name = "uk_books_isbn", columnNames = "isbn"),
        @UniqueConstraint(
                name = "uk_books_name_author_date",
                columnNames = {"name", "author", "publish_date"}
        )
    })
@Data
public class Book {

    /** Primary key, auto-generated by the database */
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** International Standard Book Number, unique identifier, immutable, 13 characters */
    @Column(nullable = false, unique = true, updatable = false, length = 13)
    private String isbn;

    /** Book title/name, required, max 255 characters */
    @Column(nullable = false, length = 255)
    private String name;

    /** Author name, required, max 255 characters */
    @Column(nullable = false, length = 255)
    private String author;

    /** Publication date, required */
    @Column(name = "publish_date", nullable = false)
    private LocalDate publishDate;

    /** Book price, required, precision 10 digits total, 2 decimal places */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    /** Book type enumeration, stored as string, required, max 16 characters */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private BookType bookType;
}